version: '3'

networks:
  mynetwork:
    driver: bridge


services:

  db:
    image: mysql:5.7
    networks:
      - mynetwork
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: commerces
      MYSQL_ROOT_PASSWORD: root 

  app:
    image: faroukboussaid/tqf:v2
    ports: 
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: commerces

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  db_data: {}